"""E2b: what the conditioning mechanism buys, measured against two ablated arms.

Three arms, three seeds each, identical training distribution and budget:

    film    token -> FiLM modulation of the DAN layer inputs   (the paper's)
    blind   no token anywhere: channels-only                   (jointblind-*)
    concat  token broadcast to the attention heads, no FiLM    (joint-concat-*)

Two questions, each answered by one paired comparison against film:

    Q1  Does the explicit token improve anything beyond the local magnitude
        channels?                              film vs blind.
    Q2  Does FiLM offer value over a simpler descriptor-injection mechanism?
        film vs concat.

Both are decided against the paper's pre-specified +/-1% equivalence margin, on
the six training regimes pooled and on each held-out composition (SW, LSW)
separately, paired by training seed so that training noise is differenced out
rather than pooled in. Uncertainty is a nested bootstrap over seeds AND
instances; per-seed means are printed so that three seeds read as three runs
and not as a large sample.

An EQUIVALENT verdict is a result, not a null: it says the token is an
explicit, auditable configuration interface rather than an accuracy mechanism.
The margin is fixed before the comparison, so equivalence and superiority are
decided by the same rule.

Usage: python scripts/p23_conditioning.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from macro_io import emit, refuse  # noqa: E402

RES = 'test_results/FAMILY/10x25'
TRAIN6 = ['N', 'L', 'S', 'W', 'LS', 'LW']
HELD = ['SW', 'LSW']
SEEDS = ['s301', 's302', 's303']
MARGIN = 1.0            # the paper's pre-specified equivalence margin, percent

ARMS = {
    'film':   {'s301': 'joint-v1', 's302': 'joint-v1-s302', 's303': 'joint-v1-s303'},
    'blind':  {'s301': 'jointblind-v1', 's302': 'jointblind-v1-s302',
               's303': 'jointblind-v1-s303'},
    'concat': {s: f'joint-concat-{s}' for s in SEEDS},
}
rng = np.random.default_rng(7)


def arr(suffix, r):
    p = f'{RES}/Result_greedy+10x25+family+{suffix}_{r}.npy'
    if not os.path.exists(p):
        return None
    a = np.load(p)
    return (a[:, 0] if a.ndim > 1 else a).astype(float)


miss = [f'{arm}/{s} ({suf})' for arm, bys in ARMS.items()
        for s, suf in bys.items() if arr(suf, 'SW') is None]
if miss:
    refuse('paper/macros_cond.tex',
           'conditioning arms not evaluated yet:\n   ' + '\n   '.join(miss) +
           '\nscripts/run_ablations.sh trains them; scripts/run_evals.sh '
           'evaluates them.\nRefusing a partial comparison. Every arm must carry '
           'the same seeds: an arm short a seed\nis compared on a different amount '
           'of evidence, which averages training noise out of\none side only and '
           'can move the verdict across the equivalence margin.')


def gaps_by_seed(arm, regimes):
    """Per-seed per-instance relative gap of `arm` vs film, %; positive = worse."""
    out = {}
    for s in SEEDS:
        d = [100.0 * (arr(ARMS[arm][s], r) - arr(ARMS['film'][s], r))
             / arr(ARMS['film'][s], r) for r in regimes]
        out[s] = np.concatenate(d)
    return out


def nested_ci(by_seed, n=20000):
    """Bootstrap over seeds, then instances within each drawn seed."""
    means = np.array([by_seed[s].mean() for s in SEEDS])
    bs = np.empty(n)
    for b in range(n):
        pick = rng.integers(0, len(SEEDS), len(SEEDS))
        vals = [by_seed[SEEDS[k]] for k in pick]
        bs[b] = np.mean([v[rng.integers(0, v.size, v.size)].mean() for v in vals])
    return float(means.mean()), float(np.percentile(bs, 2.5)), \
        float(np.percentile(bs, 97.5))


def verdict(lo, hi):
    if -MARGIN < lo and hi < MARGIN:
        return f'EQUIVALENT within +/-{MARGIN:.0f}%'
    if hi < 0:
        return 'the ablated arm is BETTER (superiority, CI < 0)'
    if lo > 0:
        return 'film is BETTER (superiority, CI > 0)'
    return 'INCONCLUSIVE: the CI spans the margin'


print('E2b: what does the conditioning mechanism buy?')
print(f'Paired by training seed, {len(SEEDS)} seeds, nested bootstrap over '
      f'seeds and instances, pre-specified margin +/-{MARGIN:.0f}%.\n')

scopes = [('Train', 'six training regimes pooled', TRAIN6),
          ('Sw', 'held-out SW', ['SW']),
          ('Lsw', 'held-out LSW', ['LSW'])]
macros = ['% auto-generated by scripts/p23_conditioning.py -- do not hand-edit']
for arm, q in (('blind', 'Q1 token vs channels-only'),
               ('concat', 'Q2 FiLM vs simple injection')):
    print(f'{q}:  {arm} vs film  (positive = {arm} worse)')
    for key, label, regimes in scopes:
        by = gaps_by_seed(arm, regimes)
        m, lo, hi = nested_ci(by)
        per = '  '.join(f'{s}={by[s].mean():+.2f}' for s in SEEDS)
        print(f'  {label:28s} {m:+.2f}%  CI [{lo:+.2f}, {hi:+.2f}]  '
              f'-> {verdict(lo, hi)}')
        print(f'  {"":28s} per-seed: {per}')
        cap = arm.capitalize()
        macros += [(f'Cond{cap}{key}Delta', f'{m:+.2f}'),
                   (f'Cond{cap}{key}Lo', f'{lo:+.2f}'),
                   (f'Cond{cap}{key}Hi', f'{hi:+.2f}')]
    print()

macros.append(('CondSeeds', str(len(SEEDS))))
emit('paper/macros_cond.tex', macros)
