"""Fuzz the three reward envelopes and emit the E7 protocol macros.

E7's premise must itself be verified, not asserted: the 'max' arm is only a
valid test of admissibility if it (a) over-estimates realized schedules (so it
is genuinely inadmissible) while (b) remaining terminally exact (so Proposition
1 still aligns its reward). This script measures both on rollouts and emits the
numbers the E7 protocol paragraph cites.

Units matter here and were the source of two wrong probes: op_ct_lb lives in
normalized time while current_makespan is raw, so the realized schedule must be
read as max(op_ct), the bound's own units.

Usage: OMP_NUM_THREADS=2 taskset -c 4-5 python scripts/p24_envelope_fuzz.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.getcwd())
from macro_io import emit  # noqa: E402

import torch  # noqa: E402
torch.set_default_device('cpu')

from constraint_family.fjsp_env_family import FJSPEnvFamily  # noqa: E402
from constraint_family.descriptor import make_descriptor  # noqa: E402
from ppvc_instance_generator import (ppvc_instance_generator,  # noqa: E402
                                     build_factory, DEFAULT_FACTORY)
from common_utils import heuristic_select_action  # noqa: E402

mch_type, _ = build_factory(DEFAULT_FACTORY)
n_m = len(mch_type)
N = 25
res = {}
for mode in ('min', 'zero', 'max'):
    over = tex = 0
    worst = 0.0
    for i in range(N):
        jl, pt, meta = ppvc_instance_generator(
            n_modules=10, class_mix='mixed',
            station_counts=DEFAULT_FACTORY, seed=9000 + i)
        d = make_descriptor('LS', jl, pt, meta, n_m, seed=77000 + i)
        e = FJSPEnvFamily(10, n_m, family_mode=True)
        e.delta_mode = mode
        e.reward_delta_env = (mode != 'zero')
        e.set_initial_data([jl], [pt], descriptor_list=[d],
                           op_type_list=[meta['op_type']],
                           mch_type_list=[meta['mch_type']])
        lb0 = float(e.init_quality[0])
        np.random.seed(3)
        while not e.done().all():
            e.step(np.array([heuristic_select_action('MWKR', e)]))
        ms = float(np.max(e.op_ct[0]))          # realized, in the bound's units
        lbT = float(np.max(e.op_ct_lb, axis=1)[0])
        if lb0 > ms + 1e-6:
            over += 1
            worst = max(worst, 100.0 * (lb0 - ms) / ms)
        if abs(lbT - ms) > 1e-4:
            tex += 1
    res[mode] = (over, worst, tex)
    print(f'{mode:5s}  over-estimates a realized schedule {over}/{N} '
          f'(worst {worst:+.1f}%)   terminal-exactness failures {tex}/{N}')

ok = (res['min'][0] == 0 and res['zero'][0] == 0 and res['max'][0] > 0
      and all(v[2] == 0 for v in res.values()))
if not ok:
    raise SystemExit('*** the arms do not have the properties E7 requires; '
                     'the experiment text must not claim them')

emit('paper/macros_fuzz.tex', [
    '% auto-generated by scripts/p24_envelope_fuzz.py -- do not hand-edit',
    ('FuzzN', str(N)),
    ('FuzzMaxOver', str(res['max'][0])),
    ('FuzzMaxWorstPct', f"{res['max'][1]:.1f}"),
])
