"""P35: CP-SAT model size, and what the short-budget setup tiers actually measure.

WHY. The 5 s CP-SAT result on the setup regimes measures this formulation, not
the problem: the sequence-dependent setups are encoded as one AddCircuit per
machine over that machine's eligible operations, which is large, and at 5 s the
solve is still in early search. The paper says so, and this script is the number
behind the sentence. This
script states that in numbers, all of which are read back (not typed): the model
size for a representative setup instance, and the 5 s solver status across the four
setup-bearing regimes.

Emits paper/macros_cpsat.tex. Every number is asserted against the released solver
outputs or read from a freshly built model, so a stale claim cannot survive.

Usage: python scripts/p36_cpsat_modelsize.py
"""
import glob
import json
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ortools.sat.python import cp_model

from constraint_family.cpsat_family import family_solver
from constraint_family.descriptor import ConstraintDescriptor
from ppvc_instance_generator import load_instance

REP = 'data/FAMILY/10x25/desc/S/instance_000.desc.json'   # representative setup instance
FIVE = 'or_solution/FAMILY/10x25_fairwarm5s'               # the 5 s fair-warm campaign
SETUP_REGIMES = ['S', 'LS', 'SW', 'LSW']


class _Captured(Exception):
    pass


def model_size():
    """Build the CP-SAT model for a representative setup instance and read its size
    off the proto, without paying for the solve (we raise once stats are captured)."""
    cap = {}
    orig = cp_model.CpSolver.Solve

    def patched(self, model, *a, **k):
        p = model.Proto()
        cap['nvars'] = len(p.variables)
        cap['ncons'] = len(p.constraints)
        cap['circuits'] = sum(c.WhichOneof('constraint') == 'circuit'
                              for c in p.constraints)
        raise _Captured

    cp_model.CpSolver.Solve = patched
    try:
        d = json.load(open(REP))
        jl, pt, _ = load_instance(d['base_instance'])
        cap['ops'], cap['machines'] = int(pt.shape[0]), int(pt.shape[1])
        try:
            family_solver(jl, pt, ConstraintDescriptor.from_json(d), time_limit=1.0)
        except _Captured:
            pass
    finally:
        cp_model.CpSolver.Solve = orig
    return cap


def five_second_status():
    """On the setup regimes, how many of the n instances end at 5 s with no better
    incumbent than the warm start (UNKNOWN) and a zero lower bound?"""
    per = {}
    for r in SETUP_REGIMES:
        fs = sorted(glob.glob(f'{FIVE}/{r}/*.json'))
        assert fs, f'no 5 s results for regime {r} under {FIVE}'
        unknown = boundzero = 0
        for f in fs:
            dd = json.load(open(f))
            unknown += (dd.get('status') == 'UNKNOWN')
            boundzero += (dd.get('bound', 1.0) <= 1e-3)
        per[r] = (len(fs), unknown, boundzero)
    return per


if __name__ == '__main__':
    cap = model_size()
    per = five_second_status()

    ns = {n for n, _, _ in per.values()}
    assert len(ns) == 1, f'setup regimes have unequal instance counts: {per}'
    n = ns.pop()
    all_unknown = all(u == n for _, u, _ in per.values())
    all_boundzero = all(b == n for _, _, b in per.values())
    # The prose claims "every instance, every setup regime". Refuse to print it
    # unless the released outputs actually bear it out.
    assert all_unknown, f'not all setup 5 s solves are UNKNOWN: {per}'
    assert all_boundzero, f'not all setup 5 s solves have a zero bound: {per}'

    out = 'paper/macros_cpsat.tex'
    with open(out, 'w') as fh:
        fh.write('% auto-generated by scripts/p36_cpsat_modelsize.py -- do not hand-edit\n')
        fh.write(f'\\newcommand{{\\CpsatOps}}{{{cap["ops"]}}}\n')
        fh.write(f'\\newcommand{{\\CpsatMachines}}{{{cap["machines"]}}}\n')
        fh.write(f'\\newcommand{{\\CpsatVars}}{{{cap["nvars"]:,}}}\n'.replace(',', '{,}'))
        fh.write(f'\\newcommand{{\\CpsatCons}}{{{cap["ncons"]:,}}}\n'.replace(',', '{,}'))
        fh.write(f'\\newcommand{{\\CpsatCircuits}}{{{cap["circuits"]}}}\n')
        fh.write(f'\\newcommand{{\\CpFiveSetupN}}{{{len(SETUP_REGIMES)}}}\n')
        fh.write(f'\\newcommand{{\\CpFiveSetupUnknown}}{{{n}}}  % of {n}, every setup regime\n')
    print(f'model: {cap["nvars"]:,} vars, {cap["ncons"]:,} constraints, '
          f'{cap["circuits"]} circuits ({cap["ops"]} ops, {cap["machines"]} machines)')
    print('5 s setup status:', {r: f'{u}/{nn} UNKNOWN, {b}/{nn} bound=0'
                                 for r, (nn, u, b) in per.items()})
    print(f'wrote {out}')
