"""P38: residual optimality gaps for the fair-warm CP-SAT tiers.

Where the paper says CP-SAT proves optimality on some
instances, it also report the residual optimality gap on the REMAINING
instances (the ones the solver did not close within the budget). This script
emits those numbers as macros, per regime and pooled, for the two tiers the
paper quotes: 30 s (all 100 instances of every regime) and 300 s (the fixed
30-instance prefix of every regime).

DEFINITIONS.
  credited value : min(warm start, search) -- exactly the number Table I reports.
                   AddHint is a suggestion, not a solution, so a short solve can
                   report a value worse than the complete feasible schedule it was
                   handed; the Protocol credits the better of the two. (In this
                   incumbent-retaining campaign the search never returns worse than
                   the hint, so the min is the search value, but it is taken
                   explicitly so this script cannot drift from Table I.)
  bound          : BestObjectiveBound, the solver's proven lower bound.
  proved optimal : status == 'OPTIMAL'. The solver closed the gap.
  residual gap   : 100 * (credited - bound) / bound, in percent. Reported over the
                   REMAINING instances (status != OPTIMAL), which is what the
                   headline quotes; the proved-optimal instances have gap 0 by
                   construction and are counted separately.

GUARD. bound must not exceed the credited value on any instance: a lower bound
above the incumbent is impossible and would mean the files were misread. The
script asserts this and aborts loudly on any violation.

Writes paper/macros_optgap.tex. Usage: python scripts/p38_optgap.py
"""
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np  # noqa: E402

OR = 'or_solution/FAMILY'
REGIMES = ['N', 'L', 'S', 'W', 'LS', 'LW', 'SW', 'LSW']
# The repaired best-of-four warm-start cache (scripts/p41_repaired_warm_cache.py).
# The 30s tier was re-solved from this hint (10x25_fairwarmR30s), so its objective,
# warm_makespan and bound all come from that rerun. The 300s tier was not re-solved:
# its bound is the original solve's, and its credited value is floored at the
# repaired hint (see load_tier).
_REPAIRED = json.load(open(f'{OR}/warmstart_cache_repaired/makespans.json'))
# tier macro-word -> config. dir: directory read; expect: instances/regime;
# recredit: floor the original credited value at the repaired hint (the tier was
# NOT re-solved); label: display name for prints and comments.
TIERS = {
    'Thirty': dict(dir='10x25_fairwarmR30s', expect=100, recredit=False, label='30s'),
    'ThreeHundred': dict(dir='10x25_fairwarm300s', expect=30, recredit=True,
                         label='300s'),
}


def load_tier(cfg):
    """Per regime: (credited[], bound[], proved-optimal mask[]). Asserts shape
    and the lower-bound guard."""
    out = {}
    for r in REGIMES:
        files = sorted(glob.glob(f"{OR}/{cfg['dir']}/{r}/*.json"))
        cred, bnd, opt = [], [], []
        for f in files:
            d = json.load(open(f))
            obj, warm, b = d['objective'], d['warm_makespan'], d['bound']
            if obj is None:
                raise SystemExit(f'{f}: objective is null -- an UNKNOWN solve has '
                                 f'no credited value and must not enter the gap.')
            if cfg['recredit']:
                # Not re-solved: floor at the repaired hint (<= the original hint),
                # taken consistently with the original solve's own bound below.
                hint = _REPAIRED[r][d['instance']]['repaired_ms']
                c = min(hint, min(obj, warm))
            else:
                c = min(obj, warm)                # warm IS the repaired hint (rerun)
            if b > c + 1e-6:                      # THE GUARD
                raise SystemExit(
                    f'{f}: bound {b} exceeds credited value {c} -- impossible for a '
                    f'valid lower bound. The files were misread; refusing to emit.')
            cred.append(c)
            bnd.append(b)
            opt.append(d['status'] == 'OPTIMAL')
        if len(files) != cfg['expect']:
            raise SystemExit(f"{cfg['label']} {r}: found {len(files)} instances, "
                             f"expected {cfg['expect']}. Refusing to emit a ragged "
                             f"tier.")
        out[r] = (np.array(cred), np.array(bnd), np.array(opt, dtype=bool))
    return out


def gap(cred, bnd):
    return 100.0 * (cred - bnd) / bnd


macros = ['% auto-generated by scripts/p38_optgap.py -- do not hand-edit',
          '% Residual optimality gap = 100*(credited - bound)/bound, over the',
          '% instances NOT proved optimal. Credited = min(repaired warm start,',
          '% search), the same value Table I reports. Tiers: 30s (100 inst/regime,',
          '% re-solved from the repaired hint), 300s (30-instance prefix/regime,',
          '% credited value floored at the repaired hint against the original bound).']

print(f"{'tier':13} {'reg':4} {'n':>3} {'opt':>3} {'rem':>3} "
      f"{'resMean%':>9} {'resMed%':>8} {'allMean%':>9} {'allMed%':>8}")
print('-' * 70)

for word, cfg in TIERS.items():
    suffix, expect = cfg['label'], cfg['expect']
    data = load_tier(cfg)
    macros.append(f'\\newcommand{{\\OptGap{word}NPerRegime}}{{{expect}}}'
                  f'  % instances per regime in the {suffix} tier')
    pooled_res_gaps = []          # residual gaps pooled over the 8 regimes
    pooled_all_gaps = []
    pooled_opt = pooled_n = 0
    for r in REGIMES:
        cred, bnd, opt = data[r]
        all_g = gap(cred, bnd)
        res_g = all_g[~opt]                       # remaining instances only
        n_opt = int(opt.sum())
        n_rem = int((~opt).sum())
        pooled_opt += n_opt
        pooled_n += len(cred)
        pooled_all_gaps.append(all_g)
        if n_rem:
            pooled_res_gaps.append(res_g)
        res_mean = float(res_g.mean()) if n_rem else float('nan')
        res_med = float(np.median(res_g)) if n_rem else float('nan')
        print(f"{suffix:13} {r:4} {len(cred):3d} {n_opt:3d} {n_rem:3d} "
              f"{res_mean:9.2f} {res_med:8.2f} "
              f"{all_g.mean():9.2f} {np.median(all_g):8.2f}")
        macros.append(
            f'\\newcommand{{\\OptGap{word}{r}Opt}}{{{n_opt}}}')
        if n_rem:                                 # skip if a regime is fully closed
            macros.append(
                f'\\newcommand{{\\OptGap{word}{r}Mean}}{{{res_mean:.1f}}}'
                f'\\newcommand{{\\OptGap{word}{r}Med}}{{{res_med:.1f}}}'
                f'  % {r}: residual gap over {n_rem} unproved instances (mean, median %)')

    all_pool = np.concatenate(pooled_all_gaps)
    res_pool = (np.concatenate(pooled_res_gaps) if pooled_res_gaps
                else np.array([]))
    pooled_rem = pooled_n - pooled_opt
    macros += [
        f'\\newcommand{{\\OptGap{word}PooledN}}{{{pooled_n}}}'
        f'\\newcommand{{\\OptGap{word}PooledOpt}}{{{pooled_opt}}}'
        f'\\newcommand{{\\OptGap{word}PooledRem}}{{{pooled_rem}}}'
        f'  % {suffix} tier pooled over 8 regimes: total, proved optimal, remaining',
        f'\\newcommand{{\\OptGap{word}PooledMean}}{{{res_pool.mean():.1f}}}'
        f'\\newcommand{{\\OptGap{word}PooledMed}}{{{np.median(res_pool):.1f}}}'
        f'  % residual gap over the {pooled_rem} unproved instances (mean, median %)',
        f'\\newcommand{{\\OptGap{word}PooledMeanAll}}{{{all_pool.mean():.1f}}}'
        f'\\newcommand{{\\OptGap{word}PooledMedAll}}{{{np.median(all_pool):.1f}}}'
        f'  % gap over ALL {pooled_n} instances (optimal ones count as 0)',
    ]
    print(f"{suffix:13} POOL  opt={pooled_opt} rem={pooled_rem} "
          f"resMean={res_pool.mean():.2f}% resMed={np.median(res_pool):.2f}% "
          f"allMean={all_pool.mean():.2f}%")

with open('paper/macros_optgap.tex', 'w') as f:
    f.write('\n'.join(macros) + '\n')
print('\nwrote paper/macros_optgap.tex')
