"""P45: the deployment artifact, regime by regime.

The paper recommends shipping the token-blind policy, but its specialist-parity
evidence (E1) is measured on the conditioned joint. This script closes that gap
from results already on disk: for every regime it compares, with the same
campaign, the same three seeds pooled on both sides, and the paper's
pre-specified +/-1% margin,

    blind  vs film   does dropping the token and the FiLM pathway cost anything,
                     regime by regime (p23 answers this pooled; here per regime);
    blind  vs spec   does the SHIPPED artifact hold the specialist parity that
                     E1 established for the conditioned joint (the N specialist
                     is E1's control; the deployment catalogue needs none);
    concat vs film   does the simpler injection trail FiLM anywhere.

Conventions are p23_conditioning.py's exactly: per-instance relative gaps in
percent with the FIRST-NAMED arm in the numerator (positive = first arm worse),
a nested bootstrap over training seeds and then instances (B=20000, rng seed 7),
and equivalence decided before superiority. Writes the full tabular to
paper/tables/blind_table.tex and summary counts to paper/macros_blind.tex.

Usage: python scripts/p45_blind_perregime.py
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from macro_io import emit, refuse  # noqa: E402

RES = 'test_results/FAMILY/10x25'
REGIMES = ['N', 'L', 'S', 'W', 'LS', 'LW', 'SW', 'LSW']
TRAIN6 = ['N', 'L', 'S', 'W', 'LS', 'LW']
SEEDS = ['s301', 's302', 's303']
MARGIN = 1.0            # the paper's pre-specified equivalence margin, percent

ARMS = {
    'film':   {'s301': 'joint-v1', 's302': 'joint-v1-s302', 's303': 'joint-v1-s303'},
    'blind':  {'s301': 'jointblind-v1', 's302': 'jointblind-v1-s302',
               's303': 'jointblind-v1-s303'},
    'concat': {s: f'joint-concat-{s}' for s in SEEDS},
}
SPEC = {r: {'s301': f'spec-{r}', 's302': f'spec-{r}-s302',
            's303': f'spec-{r}-s303'} for r in REGIMES}
rng = np.random.default_rng(7)


def arr(suffix, r):
    p = f'{RES}/Result_greedy+10x25+family+{suffix}_{r}.npy'
    if not os.path.exists(p):
        return None
    a = np.load(p)
    return (a[:, 0] if a.ndim > 1 else a).astype(float)


miss = [f'{arm}/{s}' for arm, bys in ARMS.items()
        for s, suf in bys.items() if arr(suf, 'SW') is None]
miss += [f'spec-{r}/{s}' for r, bys in SPEC.items()
         for s, suf in bys.items() if arr(suf, r) is None]
if miss:
    refuse('paper/macros_blind.tex',
           'arms not evaluated yet:\n   ' + '\n   '.join(miss) +
           '\nRefusing a partial comparison: an arm short a seed is compared on '
           'a different\namount of evidence, which averages training noise out '
           'of one side only.')


def gap_by_seed(a_by, b_by, r):
    """Per-seed per-instance relative gap a vs b on regime r, %; + = a worse."""
    return {s: 100.0 * (arr(a_by[s], r) - arr(b_by[s], r)) / arr(b_by[s], r)
            for s in SEEDS}


def nested_ci(by_seed, n=20000):
    means = np.array([by_seed[s].mean() for s in SEEDS])
    bs = np.empty(n)
    for b in range(n):
        pick = rng.integers(0, len(SEEDS), len(SEEDS))
        vals = [by_seed[SEEDS[k]] for k in pick]
        bs[b] = np.mean([v[rng.integers(0, v.size, v.size)].mean() for v in vals])
    return float(means.mean()), float(np.percentile(bs, 2.5)), \
        float(np.percentile(bs, 97.5))


def verdict(lo, hi):
    if -MARGIN < lo and hi < MARGIN:
        return 'equivalent'
    if hi < 0:
        return 'ahead'      # the first-named arm is better, CI clear of zero
    if lo > 0:
        return 'behind'
    return 'undecided'


print('P45: the shipped token-blind policy, regime by regime '
      f'(margin +/-{MARGIN:.0f}%, {len(SEEDS)} seeds pooled on both sides)\n')
cells = {}
counts = {('blind', 'film'): {}, ('blind', 'spec'): {}, ('concat', 'film'): {}}
for r in REGIMES:
    row = {}
    pairs = [('blind', 'film', ARMS['blind'], ARMS['film'])]
    if r in SPEC:
        pairs.append(('blind', 'spec', ARMS['blind'], SPEC[r]))
    pairs.append(('concat', 'film', ARMS['concat'], ARMS['film']))
    for a, b, a_by, b_by in pairs:
        m, lo, hi = nested_ci(gap_by_seed(a_by, b_by, r))
        v = verdict(lo, hi)
        row[(a, b)] = (m, lo, hi, v)
        counts[(a, b)][r] = v
        print(f'  {r:4s} {a}-{b}: {m:+.2f}%  [{lo:+.2f}, {hi:+.2f}]  {v}')
    cells[r] = row

# ---- the tabular, header included (do not hand-edit the output) ----
def cell(row, key):
    if key not in row:
        return '--- & ---'
    m, lo, hi, v = row[key]
    return (f'${m:+.2f}$ {{\\scriptsize$[{lo:+.2f},{hi:+.2f}]$}} & {v}')


lines = [
    '% auto-generated by scripts/p45_blind_perregime.py -- do not hand-edit',
    '\\begin{tabular}{lllllll}',
    '\\toprule',
    '& \\multicolumn{2}{c}{token-blind vs.\\ conditioned}'
    ' & \\multicolumn{2}{c}{token-blind vs.\\ specialist}'
    ' & \\multicolumn{2}{c}{direct vs.\\ FiLM} \\\\',
    '\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}',
    'regime & $\\Delta$ (\\%) & verdict & $\\Delta$ (\\%) & verdict'
    ' & $\\Delta$ (\\%) & verdict \\\\',
    '\\midrule',
]
for r in REGIMES:
    if r == 'SW':
        lines.append('\\midrule')
    lines.append(f'${r}$ & ' + cell(cells[r], ('blind', 'film')) + ' & ' +
                 cell(cells[r], ('blind', 'spec')) + ' & ' +
                 cell(cells[r], ('concat', 'film')) + ' \\\\')
lines += ['\\bottomrule', '\\end{tabular}']
os.makedirs('paper/tables', exist_ok=True)
with open('paper/tables/blind_table.tex', 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('\nwrote paper/tables/blind_table.tex')

# ---- summary macros for the prose ----
def n_of(pair, vs, regimes):
    return sum(1 for r in regimes if counts[pair].get(r) in vs)


spec_regs = [r for r in REGIMES if r in SPEC]
macros = [
    '% auto-generated by scripts/p45_blind_perregime.py -- do not hand-edit',
    ('BlindFilmOkN', str(n_of(('blind', 'film'), {'equivalent', 'ahead'},
                             REGIMES))),
    ('BlindFilmN', str(len(REGIMES))),
    ('BlindFilmAheadN', str(n_of(('blind', 'film'), {'ahead'}, REGIMES))),
    ('ConcatFilmAheadN', str(n_of(('concat', 'film'), {'ahead'}, REGIMES))),
    ('BlindSeeds', str(len(SEEDS))),
    ('BlindSpecEquivTrainN', str(n_of(('blind', 'spec'),
                                      {'equivalent'}, TRAIN6))),
    ('BlindSpecTrainN', str(len([r for r in TRAIN6 if r in SPEC]))),
    ('BlindSpecHeldEquivN', str(n_of(('blind', 'spec'), {'equivalent'},
                                     ['SW', 'LSW']))),
    ('BlindSpecBehindN', str(n_of(('blind', 'spec'), {'behind'}, spec_regs))),
    ('ConcatFilmOkN', str(n_of(('concat', 'film'), {'equivalent', 'ahead'},
                               REGIMES))),
]
w = cells['W'].get(('blind', 'spec'))
if w:
    macros += [('BlindSpecWDelta', f'{w[0]:+.2f}'),
               ('BlindSpecWLo', f'{w[1]:+.2f}'),
               ('BlindSpecWHi', f'{w[2]:+.2f}')]
emit('paper/macros_blind.tex', macros)
